const Map<String, String> arabic = {
  'skip': 'تخطي',
  'onboardingTitle1': 'مرحباً بكم في المطعم',
  'onboardingSubTitle1': 'لنبدأ رحلتك معنا نحن في انتظارك',
  'onboardingTitle2': 'استكشف الطعام',
  'onboardingSubTitle2': 'استكشف عالم الطعام معنا واكتشف نكهات ومأكولات جديدة ستسعد براعم التذوق لديك.',
  'onboardingTitle3': 'مرحبا بكم في مطبخنا',
  'onboardingSubTitle3': 'مرحباً بكم في مطبخنا حيث نقدم لكم أفضل الأطباق من جميع أنحاء العالم ونجعلها متاحة لكم في متناول أيديكم.',
  'error': 'خطأ',
  'somethingWentWrong':'لقد حدث خطأ ما',
  'warning':'تحذير',
  'loginError': 'خطأ في تسجيل الدخول',
  'success': 'نجاح',
  'loginSuccessfully': 'لقد قمت بتسجيل الدخول بنجاح.',
  'logoutSuccessfully': 'لقد قمت بتسجيل الخروج بنجاح.',
  'RatingSuccessMessage': 'تمت إضافة التقييم بنجاح.',
  'close': 'اغلاق',
  'version': 'إصدار',
  'signUpSuccessMessage': 'تم إنشاء الحساب بنجاح.',
  'loginSuccessMessage': 'لقد قمت بتسجيل الدخول بنجاح.',
  'privacyPolicy': 'سياسة الخصوصية',
  'acceptPrivacyPolicy': 'يرجى قبول سياسة الخصوصية.',
  'required': ' مطلوب.',
  'emailRequired': 'البريد الإلكتروني مطلوب.',
  'invalidEmail': 'عنوان البريد الإلكتروني غير صالح.',
  'passwordRequired': 'كلمة المرور مطلوبة.',
  'passwordLength': 'يجب أن تكون كلمة المرور مكونة من 8 أحرف على الأقل.',
  'loginTitle': 'تسجيل الدخول',
  'loginSubTitle': 'سجل دخولك الآن لتكتشف أفضل المطاعم والوجبات وتقيمها بنفسك.',
  'signUpTitle': 'سجل دخولك الآن لتكتشف أفضل المطاعم والوجبات وتقيمها بنفسك.',
  'firstName': 'الاسم الأول',
  'lastName': 'اسم العائلة',
  'email': 'البريد الألكتروني',
  'password': 'كلمة المرور',
  'rememberMe': 'تذكرني',
  'rememberMeMessage': 'تذكرني البريد الإلكتروني وكلمة المرور',
  'login': 'تسجيل الدخول',
  'signUp': 'انشاء حساب',
  'logout': 'تسجيل الخروج',
  'home': 'الصفحة الرئيسية',
  'categories': 'الفئات',
  'favorites': 'المفضلة',
  'profile': 'الملف الشخصي',
  'settings': 'الإعدادات',
  'about': 'حول',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  'add': 'إضافة',
  'cancel': 'إلغاء',
  'comments': 'التعليق',
  'addComment': 'إضافة تعليق',
  'textFieldHint': 'اكتب تعليقك هنا...',
  'language': 'اللغة',
  'darkMode': 'المظهر الداكن',
  'general': 'عام',
  'homeTitle':'مرحبا بك في مطعمنا',
  'personalInformation':'معلومات شخصيه',
  'restaurantList':'قائمة المطاعم',
  'address':'العنوان',
  'rating':'التقييم',
  'description': 'الوصف',
  'messageAboutUs': 'مرحبًا بكم في تطبيقنا الرائع! نحن ملتزمون بتقديم أفضل تجربة ممكنة لك. يعمل فريقنا بلا كلل لتقديم ميزات مبتكرة وخدمة ممتازة.',

};