const Map<String, String> english = {
  'skip': 'Skip',
  'onboardingTitle1': 'Welcome to Restaurant',
  'onboardingSubTitle1': 'Let\'s start your journey with us We are waiting for you',
  'onboardingTitle2': 'Explore Food',
  'onboardingSubTitle2': 'Explore the world of food with us and discover new flavors and cuisines that will delight your taste buds.',
  'onboardingTitle3': 'Welcome to our kitchen',
  'onboardingSubTitle3': 'Welcome to our kitchen where we bring you the best dishes from around the world and make them available to you at your fingertips.',
  'error':'Error',
  'somethingWentWrong':'Something Went Wrong',
  'warning':'Warning',
  'loginError':'Login Error',
  'success':'Success',
  'close':'Close',
  'version': 'Version',
  'signUpSuccess':'Sign Up Success',
  'signUpSuccessMessage':'Account created successfully.',
  'loginSuccess':'Login Success',
  'logoutSuccessfully':'You have successfully logged out.',
  'loginSuccessMessage':'You have successfully logged in.',
  'RatingSuccessMessage':'Rating added successfully.',
  'privacyPolicy':'Privacy Policy',
  'acceptPrivacyPolicy':'Please accept the privacy policy.',
  'required':'is required.',
  'emailRequired':'Email is required.',
  'invalidEmail':'Invalid email address.',
  'passwordRequired':'Password is required.',
  'passwordLength':'Password must be at least 8 characters long.',
  'loginTitle': 'Welcome Back!',
  'loginSubTitle': 'Log in now to discover the best restaurants and meals and rate them yourself.',
  'signUpTitle': 'Log in now to discover the best restaurants and meals and rate them yourself.',
  'firstName': 'First Name',
  'lastName': 'Last Name',
  'email': 'Email',
  'password': 'Password',
  'rememberMe': 'Remember Me',
  'rememberMeMessage': 'Remember Me Email and Password',
  'login': 'Login',
  'signUp': 'Create Account',
  'home': 'Home',
  'categories': 'Categories',
  'favorites': 'Favorites',
  'profile': 'Profile',
  'settings': 'Settings',
  'about': 'About',
  'language': 'Language',
  'darkMode': 'Dark Mode',
  'logout': 'Logout',
  'english': 'English',
  'general': 'general',
  'arabic': 'Arabic',
  'add': 'Add',
  'cancel': 'Cancel',
  'comments': 'The Comment',
  'addComment': 'Add Comment',
  'textFieldHint': 'Write your comment here...',
  'homeTitle':'Welcome to our restaurant',
  'restaurantList':'Restaurant List',
  'personalInformation':'Personal Information',
  'address':'The Address',
  'rating':'The Rating',
  'description': 'Description',
  'messageAboutUs': 'Welcome to our amazing app! We are dedicated to providing you with the best experience possible. Our team works tirelessly to bring you innovative features and excellent service.',
};